<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2OU9P92" name="com.Automation.HoroLab.TestCases.Login" tests="1" failures="1" timestamp="20 Jul 2020 14:06:33 GMT" time="153.990" errors="0">
  <testcase name="Tc_Login_002" time="153.990" classname="com.Automation.HoroLab.TestCases.Login">
    <failure type="java.lang.AssertionError" message="Fail due to exception Expected condition failed: waiting for visibility of element located by By.xpath: //*[text()=&#039;Login Failed, Reason : Bad credentials&#039;] (tried for 30 second(s) with 500 MILLISECONDS interval)">
      <![CDATA[java.lang.AssertionError: Fail due to exception Expected condition failed: waiting for visibility of element located by By.xpath: //*[text()='Login Failed, Reason : Bad credentials'] (tried for 30 second(s) with 500 MILLISECONDS interval)
	at org.testng.Assert.fail(Assert.java:94)
	at com.Automation.HoroLab.Modules.LoginPage.validateLoginErrorMsg(LoginPage.java:75)
	at com.Automation.HoroLab.TestCases.Login.Tc_Login_002(Login.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc_Login_002 -->
</testsuite> <!-- com.Automation.HoroLab.TestCases.Login -->
